language: php
php:
  - "5.5"
  - "5.4"
  - "5.3"
env:
  - DOKUWIKI=master
  - DOKUWIKI=stable
  - DOKUWIKI=old-stable
before_install:
  - "rm .gitignore"
  - "wget https://raw.github.com/splitbrain/dokuwiki-travis/master/travis.sh"
  - "wget https://raw.github.com/mark-rushakoff/OpenPhantomScripts/master/phantom-qunit.js"
  - "wget http://code.jquery.com/qunit/qunit-1.14.0.css"
  - "wget http://code.jquery.com/qunit/qunit-1.14.0.js"
install:
  - "sh travis.sh"
script:
  - "cd _test && phpunit --stderr --group plugin_siteexport"
  - "cd ../lib/plugins/siteexport && sh _test/phantomjs/runPhantomJs.sh"
